config/routes.rb
Rails.application.routes.draw do
  resources :appearances
  resources :participants
  resources :titles
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/appearance.rb
class Appearance < ApplicationRecord
  belongs_to :participant
  belongs_to :title

  enum role: { director: 0, actor: 1 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant < ApplicationRecord
end

app/models/title.rb
class Title < ApplicationRecord
  has_many :appearances, inverse_of: :title, dependent: :destroy
  has_many :participants, through: :appearances

  has_many :appearances_by_directors, -> { where(role: :director) }, class_name: 'Appearance', inverse_of: :title
  has_many :directors, through: :appearances_by_directors, class_name: 'Participant', source: :participant

  has_many :appearances_by_actors, -> { where(role: :actor) }, class_name: 'Appearance', inverse_of: :title
  has_many :actors, through: :appearances_by_actors, class_name: 'Participant', source: :participant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/appearances_controller.rb
class AppearancesController < InheritedResources::Base

  private

    def appearance_params
      params.require(:appearance).permit(:participant_id, :title_id, :role)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/participants_controller.rb
class ParticipantsController < InheritedResources::Base

  private

    def participant_params
      params.require(:participant).permit(:first_name, :last_name)
    end

end

app/controllers/titles_controller.rb
class TitlesController < InheritedResources::Base

  private

    def title_params
      params.require(:title).permit(:name, :type, :director_id, :release_year, :rating, :duration_in_minutes, :duration_seasons, :description)
    end

end

app/helpers/appearances_helper.rb
module AppearancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/appearances/_form.html.erb
<%= form_with(model: appearance) do |form| %>
  <% if appearance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appearance.errors.count, "error") %> prohibited this appearance from being saved:</h2>

      <ul>
        <% appearance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :participant_id %>
    <%= form.text_field :participant_id %>
  </div>

  <div class="field">
    <%= form.label :title_id %>
    <%= form.text_field :title_id %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.number_field :role %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appearances/edit.html.erb
<h1>Editing Appearance</h1>

<%= render 'form', appearance: @appearance %>

<%= link_to 'Show', @appearance %> |
<%= link_to 'Back', appearances_path %>

app/views/appearances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appearances</h1>

<table>
  <thead>
    <tr>
      <th>Participant</th>
      <th>Title</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appearances.each do |appearance| %>
      <tr>
        <td><%= appearance.participant_id %></td>
        <td><%= appearance.title_id %></td>
        <td><%= appearance.role %></td>
        <td><%= link_to 'Show', appearance %></td>
        <td><%= link_to 'Edit', edit_appearance_path(appearance) %></td>
        <td><%= link_to 'Destroy', appearance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appearance', new_appearance_path %>

app/views/appearances/new.html.erb
<h1>New Appearance</h1>

<%= render 'form', appearance: @appearance %>

<%= link_to 'Back', appearances_path %>

app/views/appearances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Participant:</strong>
  <%= @appearance.participant_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @appearance.title_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @appearance.role %>
</p>

<%= link_to 'Edit', edit_appearance_path(@appearance) %> |
<%= link_to 'Back', appearances_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveSearchDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/participants/_form.html.erb
<%= form_with(model: participant) do |form| %>
  <% if participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
        <% participant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participants</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.first_name %></td>
        <td><%= participant.last_name %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @participant.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @participant.last_name %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>

app/views/titles/_form.html.erb
<%= form_with(model: title) do |form| %>
  <% if title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(title.errors.count, "error") %> prohibited this title from being saved:</h2>

      <ul>
        <% title.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :director_id %>
    <%= form.text_field :director_id %>
  </div>

  <div class="field">
    <%= form.label :release_year %>
    <%= form.text_field :release_year %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
    <%= form.label :duration_in_minutes %>
    <%= form.number_field :duration_in_minutes %>
  </div>

  <div class="field">
    <%= form.label :duration_seasons %>
    <%= form.number_field :duration_seasons %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/titles/edit.html.erb
<h1>Editing Title</h1>

<%= render 'form', title: @title %>

<%= link_to 'Show', @title %> |
<%= link_to 'Back', titles_path %>

app/views/titles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Titles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Director</th>
      <th>Release year</th>
      <th>Rating</th>
      <th>Duration in minutes</th>
      <th>Duration seasons</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @titles.each do |title| %>
      <tr>
        <td><%= title.name %></td>
        <td><%= title.type %></td>
        <td><%= title.director_id %></td>
        <td><%= title.release_year %></td>
        <td><%= title.rating %></td>
        <td><%= title.duration_in_minutes %></td>
        <td><%= title.duration_seasons %></td>
        <td><%= title.description %></td>
        <td><%= link_to 'Show', title %></td>
        <td><%= link_to 'Edit', edit_title_path(title) %></td>
        <td><%= link_to 'Destroy', title, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Title', new_title_path %>

app/views/titles/new.html.erb
<h1>New Title</h1>

<%= render 'form', title: @title %>

<%= link_to 'Back', titles_path %>

app/views/titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @title.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @title.type %>
</p>

<p>
  <strong>Director:</strong>
  <%= @title.director_id %>
</p>

<p>
  <strong>Release year:</strong>
  <%= @title.release_year %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @title.rating %>
</p>

<p>
  <strong>Duration in minutes:</strong>
  <%= @title.duration_in_minutes %>
</p>

<p>
  <strong>Duration seasons:</strong>
  <%= @title.duration_seasons %>
</p>

<p>
  <strong>Description:</strong>
  <%= @title.description %>
</p>

<%= link_to 'Edit', edit_title_path(@title) %> |
<%= link_to 'Back', titles_path %>